SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(180) NOT NULL,
  email VARCHAR(255) NOT NULL,
  papel VARCHAR(80) NOT NULL DEFAULT 'Técnico de Laboratório',
  setor VARCHAR(180) NULL,
  crq VARCHAR(80) NULL,
  telefone VARCHAR(40) NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  auth_id VARCHAR(255) NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_usuarios_email (email),
  UNIQUE KEY uq_usuarios_auth_id (auth_id),
  KEY idx_usuarios_papel (papel),
  KEY idx_usuarios_setor (setor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pedidos_coleta (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(40) NOT NULL,
  laboratorio VARCHAR(180) NOT NULL,
  solicitante VARCHAR(180) NOT NULL,
  usuario_id BIGINT UNSIGNED NULL,
  tipo_residuo VARCHAR(180) NOT NULL,
  grupo VARCHAR(100) NULL,
  classe VARCHAR(100) NULL,
  quantidade_estimada DECIMAL(14,3) NULL,
  unidade VARCHAR(20) NOT NULL DEFAULT 'kg',
  embalagem VARCHAR(180) NULL,
  local_coleta VARCHAR(255) NULL,
  data_solicitacao DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data_prevista DATETIME(3) NULL,
  data_coleta DATETIME(3) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Solicitado',
  prioridade VARCHAR(30) NOT NULL DEFAULT 'Média',
  responsavel VARCHAR(180) NULL,
  risco VARCHAR(180) NULL,
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_pedidos_codigo (codigo),
  KEY idx_pedidos_usuario (usuario_id),
  KEY idx_pedidos_status (status),
  KEY idx_pedidos_data_solicitacao (data_solicitacao),
  CONSTRAINT fk_pedidos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS coletas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pedido_id BIGINT UNSIGNED NULL,
  data_coleta DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  coletor VARCHAR(180) NULL,
  equipe VARCHAR(120) NULL,
  peso_kg DECIMAL(14,3) NULL,
  volume_l DECIMAL(14,3) NULL,
  unidades INT UNSIGNED NULL,
  destino_temporario VARCHAR(255) NULL,
  veiculo VARCHAR(180) NULL,
  mtr VARCHAR(80) NULL,
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_coletas_pedido (pedido_id),
  KEY idx_coletas_data (data_coleta),
  KEY idx_coletas_mtr (mtr),
  CONSTRAINT fk_coletas_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos_coleta (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tratamentos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(40) NOT NULL,
  pedido_id BIGINT UNSIGNED NULL,
  residuo VARCHAR(255) NOT NULL,
  grupo VARCHAR(100) NULL,
  metodo VARCHAR(180) NULL,
  quantidade_entrada DECIMAL(14,3) NULL,
  unidade VARCHAR(20) NOT NULL DEFAULT 'kg',
  quantidade_saida DECIMAL(14,3) NULL,
  eficiencia DECIMAL(7,3) NULL,
  data_inicio DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data_conclusao DATETIME(3) NULL,
  operador VARCHAR(180) NULL,
  responsavel_tecnico VARCHAR(180) NULL,
  destino_final VARCHAR(255) NULL,
  cnpj_destinador VARCHAR(30) NULL,
  mtr VARCHAR(80) NULL,
  certificado VARCHAR(100) NULL,
  custo DECIMAL(14,2) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Agendado',
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_tratamentos_codigo (codigo),
  KEY idx_tratamentos_pedido (pedido_id),
  KEY idx_tratamentos_status (status),
  KEY idx_tratamentos_data_inicio (data_inicio),
  CONSTRAINT fk_tratamentos_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos_coleta (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS solventes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(40) NOT NULL,
  nome VARCHAR(180) NOT NULL,
  formula VARCHAR(100) NULL,
  cas VARCHAR(40) NULL,
  categoria VARCHAR(100) NOT NULL DEFAULT 'Não Halogenado',
  pureza DECIMAL(7,3) NULL,
  volume_total_l DECIMAL(14,3) NULL,
  volume_restante_l DECIMAL(14,3) NULL,
  volume_recuperado_l DECIMAL(14,3) NULL,
  embalagem VARCHAR(180) NULL,
  laboratorio VARCHAR(180) NULL,
  localizacao VARCHAR(255) NULL,
  data_recebimento DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data_validade DATETIME(3) NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Em Estoque',
  inflamavel TINYINT(1) NOT NULL DEFAULT 0,
  responsavel VARCHAR(180) NULL,
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_solventes_codigo (codigo),
  KEY idx_solventes_validade (data_validade),
  KEY idx_solventes_status (status),
  KEY idx_solventes_laboratorio (laboratorio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reagentes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(40) NOT NULL,
  nome VARCHAR(180) NOT NULL,
  formula VARCHAR(100) NULL,
  cas VARCHAR(40) NULL,
  fabricante VARCHAR(180) NULL,
  lote VARCHAR(100) NULL,
  quantidade DECIMAL(14,3) NULL,
  unidade VARCHAR(20) NOT NULL DEFAULT 'g',
  laboratorio VARCHAR(180) NULL,
  localizacao VARCHAR(255) NULL,
  classe_risco VARCHAR(100) NOT NULL DEFAULT 'Irritante',
  data_aquisicao DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data_validade DATETIME(3) NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Ativo',
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_reagentes_codigo (codigo),
  KEY idx_reagentes_validade (data_validade),
  KEY idx_reagentes_status (status),
  KEY idx_reagentes_laboratorio (laboratorio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vidrarias (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(40) NOT NULL,
  tipo VARCHAR(120) NOT NULL,
  laboratorio VARCHAR(180) NULL,
  contaminante VARCHAR(180) NULL,
  classe_contaminante VARCHAR(100) NULL,
  nivel_contaminacao VARCHAR(40) NOT NULL DEFAULT 'Médio',
  quantidade INT UNSIGNED NOT NULL DEFAULT 1,
  data_registro DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data_descontaminacao DATETIME(3) NULL,
  metodo_descontaminacao VARCHAR(180) NULL,
  responsavel VARCHAR(180) NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Aguardando Descontaminação',
  destino VARCHAR(255) NULL,
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_vidrarias_codigo (codigo),
  KEY idx_vidrarias_status (status),
  KEY idx_vidrarias_data (data_registro),
  KEY idx_vidrarias_laboratorio (laboratorio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS indicadores_mensais (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mes TINYINT UNSIGNED NOT NULL,
  ano SMALLINT UNSIGNED NOT NULL,
  acidentes INT UNSIGNED NOT NULL DEFAULT 0,
  treinamentos INT UNSIGNED NOT NULL DEFAULT 0,
  custo_operacional DECIMAL(14,2) NOT NULL DEFAULT 0,
  destinacao_correta_pct DECIMAL(7,3) NULL,
  observacoes TEXT NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_indicadores_mes_ano (mes, ano),
  KEY idx_indicadores_ano (ano)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notificacoes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo VARCHAR(100) NOT NULL DEFAULT 'Aviso',
  severidade VARCHAR(30) NOT NULL DEFAULT 'info',
  titulo VARCHAR(255) NOT NULL,
  mensagem TEXT NULL,
  origem VARCHAR(80) NULL,
  origem_id VARCHAR(80) NULL,
  lida TINYINT(1) NOT NULL DEFAULT 0,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_notificacoes_lida_data (lida, criado_em),
  KEY idx_notificacoes_origem (origem, origem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS historico (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tabela VARCHAR(80) NOT NULL,
  registro_id VARCHAR(80) NOT NULL,
  registro_codigo VARCHAR(100) NULL,
  acao VARCHAR(20) NOT NULL,
  descricao VARCHAR(500) NOT NULL,
  usuario VARCHAR(180) NOT NULL,
  usuario_email VARCHAR(255) NULL,
  dados_anteriores JSON NULL,
  dados_novos JSON NULL,
  mudancas JSON NULL,
  criado_em DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_historico_tabela_registro (tabela, registro_id),
  KEY idx_historico_data (criado_em),
  KEY idx_historico_usuario (usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
